// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ArtistResponse = { id: string; name: string; albumCount: bigint; trackCount: bigint };
