// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SortDir } from './sort-dir';

export type FilteredPaginationParams = {
	limit: number;
	offset: number;
	/**
	 * base64url-encoded JSON FilterNode
	 */
	f: string | null;
	sort: string | null;
	dir: SortDir | null;
};
