// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SortDir } from './sort-dir';

export type SearchPaginationParams = {
	limit: number;
	offset: number;
	/**
	 * Optional case-insensitive `q` text query.
	 */
	q: string | null;
	sort: string | null;
	dir: SortDir | null;
};
