// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Field = 'text' | 'tag' | 'album' | 'artist' | 'year' | 'durationMs' | 'favorite';
