// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FilterValue =
	| { kind: 'text'; value: string }
	| { kind: 'id'; value: string }
	| { kind: 'ids'; value: Array<string> }
	| { kind: 'intRange'; min: bigint | null; max: bigint | null }
	| { kind: 'bool'; value: boolean };
