// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Field } from './field';
import type { FilterValue } from './filter-value';
import type { GroupOp } from './group-op';
import type { Operator } from './operator';

/**
 * Recursive filter tree.
 *
 * `negate` on either variant wraps the emitted SQL fragment in `NOT (...)`.
 */
export type FilterNode =
	| { kind: 'group'; op: GroupOp; negate: boolean; children: Array<FilterNode> }
	| { kind: 'leaf'; field: Field; op: Operator; value: FilterValue; negate: boolean };
