// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserPreferences } from '../user/user-preferences';

export type CurrentUserResponse = {
	name: string;
	email: string;
	role: string;
	preferences: UserPreferences;
};
