// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaginatedResponse } from '../common/paginated-response';
import type { PlaylistResponse } from './playlist-response';

export type GetPlaylistsResponse = PaginatedResponse<PlaylistResponse>;
