// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlaylistResponse = {
	id: string;
	name: string;
	trackCount: bigint;
	totalDurationMs: bigint;
	createdAt: string;
};
