// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaylistTrackAlbumResponse } from './playlist-track-album-response';
import type { PlaylistTrackArtistResponse } from './playlist-track-artist-response';

export type PlaylistTrackResponse = {
	id: string;
	title: string;
	artist: PlaylistTrackArtistResponse | null;
	album: PlaylistTrackAlbumResponse | null;
	trackNo: number | null;
	disc: number | null;
	durationMs: number;
	format: string;
	codec: string;
	bitrate: number | null;
	filePath: string;
	originalTitle: string | null;
	originalArtist: string | null;
	originalAlbum: string | null;
	playlistTrackId: string;
	position: number;
	addedAt: string;
};
