// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterNode } from '../../filter/filter-node';

export type CreatePlaylistParams = {
	name: string;
	/**
	 * If present, creates a dynamic playlist whose tracks are derived from
	 * this filter tree. Omit for a normal manual playlist.
	 */
	filterDefinition: FilterNode | null;
};
