// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReorderTrackParams = {
	/**
	 * The track_id to insert after. None means move to front.
	 */
	afterId: string | null;
};
