// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TagCategoryResponse = {
	id: string;
	name: string;
	color: string | null;
	position: number;
	tagCount: bigint;
	createdAt: string;
	updatedAt: string;
};
