// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlbumResponse } from '../album/album-response';
import type { PlaylistResponse } from '../playlist/playlist-response';

/**
 * Heterogeneous homepage item — either an album or a playlist. Used by
 * "Listen again" and "Forgotten favorites" where both kinds of context can
 * surface in the same ordered list.
 */
export type HomeItemResponse =
	| { kind: 'album'; data: AlbumResponse }
	| { kind: 'playlist'; data: PlaylistResponse };
