// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterNode } from '../../filter/filter-node';

export type CreateAlbumCollectionParams = { name: string; filterDefinition: FilterNode };
