// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchHit } from './search-hit';

export type PaletteSearchResponse = {
	tracks: Array<SearchHit>;
	albums: Array<SearchHit>;
	artists: Array<SearchHit>;
	playlists: Array<SearchHit>;
	collections: Array<SearchHit>;
};
