// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchEntityType } from './search-entity-type';

export type SearchHit = {
	id: string;
	kind: SearchEntityType;
	title: string;
	subtitle: string | null;
	score: number;
};
