// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlbumArtistResponse } from './album-artist-response';

export type AlbumResponse = {
	id: string;
	title: string;
	artist: AlbumArtistResponse | null;
	date: string | null;
	coverUrl: string | null;
	trackCount: bigint;
	totalDurationMs: bigint;
	playCount: bigint;
};
