// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateTagParams = {
	name: string | null;
	categoryId: string | null;
	clearCategory: boolean;
	color: string | null;
};
