// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PATCH semantics: any field present replaces the current value;
 * fields omitted from the request are left unchanged. Set
 * `clearCategory: true` to detach a tag from its category.
 */
export type UpdateTagParams = {
	name: string | null;
	categoryId: string | null;
	clearCategory: boolean;
	color: string | null;
};
