// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PATCH semantics: any field present replaces the current value;
 * fields omitted from the request are left unchanged.
 */
export type UpdateTagCategoryParams = { name: string | null; color: string | null };
