// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminDeletedTrackResponse = {
	fileMissing: boolean;
	id: string;
	title: string;
	sortTitle: string;
	artistId: string | null;
	albumId: string | null;
	disc: number | null;
	trackNo: number | null;
	date: string | null;
	composer: string | null;
	comment: string | null;
	originalTitle: string | null;
	originalArtist: string | null;
	originalAlbum: string | null;
	filePath: string;
	durationMs: number;
	lockedAt: string | null;
	deletedAt: string | null;
	approved: boolean;
};
