// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtistAliasResponse } from './artist-alias-response';

export type AdminArtistResponse = {
	id: string;
	name: string;
	sortName: string;
	lockedAt: string | null;
	approved: boolean;
	aliases: Array<ArtistAliasResponse>;
};
