// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminArtistResponse = {
	id: string;
	name: string;
	sortName: string;
	sourceName: string;
	lockedAt: string | null;
	approved: boolean;
};
