// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminAlbumResponse = {
	id: string;
	title: string;
	sortTitle: string;
	artistId: string | null;
	sourceTitle: string;
	sourceAlbumArtistId: string | null;
	date: string | null;
	coverPath: string | null;
	coverUrl: string | null;
	lockedAt: string | null;
};
