// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlbumAliasResponse } from './album-alias-response';

export type AdminAlbumResponse = {
	id: string;
	title: string;
	sortTitle: string;
	artistId: string | null;
	date: string | null;
	coverPath: string | null;
	coverUrl: string | null;
	lockedAt: string | null;
	approved: boolean;
	aliases: Array<AlbumAliasResponse>;
};
