// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MetadataSuggestionResponse = {
	id: string;
	entityType: string;
	entityId: string;
	source: string;
	mbid: string;
	score: number;
	rank: number;
	/**
	 * Per-entity-type payload. See `musicbrainz::mapping` for the shape:
	 * `AlbumProposal` for album suggestions, `ArtistProposal` for artists,
	 * `TrackProposal` for tracks. The frontend discriminates on `entityType`.
	 */
	proposed: Record<string, unknown>;
	status: string;
	createdAt: string;
};
