// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminAlbumResponse } from './admin-album-response';
import type { AdminArtistResponse } from './admin-artist-response';
import type { AdminTrackResponse } from './admin-track-response';

export type ReviewQueueAlbumGroup = {
	album: AdminAlbumResponse;
	artist: AdminArtistResponse | null;
	tracks: Array<AdminTrackResponse>;
};
