// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewQueueAlbumGroup } from './review-queue-album-group';
import type { ReviewQueueCounts } from './review-queue-counts';
import type { ReviewQueueStandaloneArtist } from './review-queue-standalone-artist';

export type ReviewQueueResponse = {
	albums: Array<ReviewQueueAlbumGroup>;
	standaloneArtists: Array<ReviewQueueStandaloneArtist>;
	counts: ReviewQueueCounts;
};
