// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminAlbumResponse } from './admin-album-response';
import type { AdminArtistResponse } from './admin-artist-response';
import type { AdminTrackResponse } from './admin-track-response';

export type ReviewQueueStandaloneArtist = {
	artist: AdminArtistResponse;
	tracks: Array<AdminTrackResponse>;
	trackAlbums: Array<AdminAlbumResponse>;
};
