// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminArtistResponse } from './admin-artist-response';
import type { ReviewQueueAlbumGroup } from './review-queue-album-group';
import type { ReviewQueueCounts } from './review-queue-counts';

export type ReviewQueueResponse = {
	albums: Array<ReviewQueueAlbumGroup>;
	standaloneArtists: Array<AdminArtistResponse>;
	counts: ReviewQueueCounts;
};
