// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrackResponse = {
	id: string;
	title: string;
	artist: string | null;
	album: string | null;
	trackNo: number | null;
	disc: number | null;
	durationMs: number;
	codec: string;
	bitrate: number | null;
	filePath: string;
	originalTitle: string | null;
	originalArtist: string | null;
	originalAlbum: string | null;
};
