// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackAlbumResponse } from './track-album-response';
import type { TrackArtistResponse } from './track-artist-response';

export type TrackResponse = {
	id: string;
	title: string;
	artist: TrackArtistResponse | null;
	album: TrackAlbumResponse | null;
	trackNo: number | null;
	disc: number | null;
	durationMs: number;
	format: string;
	codec: string;
	bitrate: number | null;
	filePath: string;
	originalTitle: string | null;
	originalArtist: string | null;
	originalAlbum: string | null;
	playCount: bigint;
};
