// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserPreferences } from '../../response/user/user-preferences';

export type UpdatePreferencesParams = { preferences: UserPreferences };
