// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagCategorySummaryResponse } from '../tag-category/tag-category-summary-response';

export type TagSummaryResponse = {
	id: string;
	name: string;
	categoryId: string | null;
	category: TagCategorySummaryResponse | null;
	color: string | null;
};
