// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TagResponse = {
	id: string;
	name: string;
	category: string | null;
	color: string | null;
	trackCount: bigint;
	albumCount: bigint;
	createdAt: string;
	updatedAt: string;
};
