// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagCategorySummaryResponse } from '../tag-category/tag-category-summary-response';

export type TagResponse = {
	id: string;
	name: string;
	categoryId: string | null;
	category: TagCategorySummaryResponse | null;
	color: string | null;
	trackCount: bigint;
	albumCount: bigint;
	createdAt: string;
	updatedAt: string;
};
